-- Create users table
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create members table
CREATE TABLE members (
  id SERIAL PRIMARY KEY,
  member_id INTEGER,
  status VARCHAR(50),
  first_name VARCHAR(100),
  middle_initial VARCHAR(10),
  school VARCHAR(100),
  nickname1 VARCHAR(100),
  nickname2 VARCHAR(100),
  last_name VARCHAR(100),
  married_name VARCHAR(100),
  spouse_name VARCHAR(100),
  member_type VARCHAR(50),
  address1 VARCHAR(255),
  address2 VARCHAR(255),
  address3 VARCHAR(255),
  city VARCHAR(100),
  state VARCHAR(50),
  zip_code VARCHAR(20),
  country VARCHAR(100),
  home_phone VARCHAR(50),
  work_phone VARCHAR(50),
  fax VARCHAR(50),
  mailing_option VARCHAR(10),
  email1 VARCHAR(255),
  email2 VARCHAR(255),
  member_license VARCHAR(50),
  spouse_license VARCHAR(50),
  member_ssn VARCHAR(50),
  spouse_ssn VARCHAR(50),
  located_date DATE,
  source VARCHAR(255),
  location_cost VARCHAR(50),
  graduation_year VARCHAR(20),
  ncb_graduate VARCHAR(10),
  grades_attended VARCHAR(100),
  dates_attended VARCHAR(100),
  other_school1 VARCHAR(255),
  dates_grades1 VARCHAR(100),
  other_school2 VARCHAR(255),
  dates_grades2 VARCHAR(100),
  other_school3 VARCHAR(255),
  dates_grades3 VARCHAR(100),
  parent_father VARCHAR(255),
  parent_mother VARCHAR(255),
  parent_address VARCHAR(255),
  sent_mra VARCHAR(10),
  questionnaire_date DATE,
  questionnaire_return VARCHAR(10),
  date_returned DATE,
  directory_requested VARCHAR(10),
  amount_received VARCHAR(50),
  directory_sent DATE,
  member_bio TEXT,
  spouse_bio TEXT,
  new_bio VARCHAR(10),
  comments TEXT,
  reunion_attended VARCHAR(10),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create events table
CREATE TABLE events (
  id SERIAL PRIMARY KEY,
  event_name VARCHAR(255) NOT NULL,
  event_subtitle VARCHAR(255),
  event_loc VARCHAR(255),
  event_datebeg DATE,
  event_dateend DATE,
  event_time VARCHAR(100),
  event_desc TEXT,
  event_photo1 VARCHAR(255),
  event_photo2 VARCHAR(255),
  event_photo3 VARCHAR(255),
  event_photo4 VARCHAR(255),
  event_status VARCHAR(50),
  event_moddate TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  event_moduser VARCHAR(255),
  event_sortcode INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Insert sample data for events
INSERT INTO events (
  event_name, 
  event_subtitle, 
  event_loc, 
  event_datebeg, 
  event_dateend, 
  event_time, 
  event_desc, 
  event_photo1, 
  event_status, 
  event_sortcode
) VALUES
(
  'Summer Music Festival',
  'Annual celebration of music and art',
  'Central Park',
  '2023-07-15',
  '2023-07-17',
  '10:00 AM - 10:00 PM',
  'Join us for three days of amazing music performances, art exhibitions, and food vendors.',
  'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
  'active',
  100
),
(
  'Tech Conference 2023',
  'The future of technology and innovation',
  'Convention Center',
  '2023-09-10',
  '2023-09-12',
  '9:00 AM - 6:00 PM',
  'Explore the latest trends and innovations in technology with presentations from industry leaders.',
  'https://images.unsplash.com/photo-1540575467063-178a50c2df87?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
  'active',
  200
),
(
  'Food and Wine Festival',
  'Taste exceptional cuisine and fine wines',
  'City Plaza',
  '2023-08-05',
  '2023-08-06',
  '11:00 AM - 8:00 PM',
  'Sample cuisine from top local restaurants paired with fine wines from around the world.',
  'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
  'active',
  300
); 